### ISSUE TITLE
哇

### ISSUE THREAD

**Issue by hustanhuang** [blackskygg/RollingLydia#1]
大家最爱上Lydia的课了😃

**Comment by blackskygg** [comment]
你不是隔壁班的吗

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f603.png)

**Comment by hustanhuang** [comment]
我选了她的选修批判性思维与写作的啊

CRITICAL THINKING AND WRITING

😃

**Comment by blackskygg** [comment]
噢！我想起来了。
